### ISSUE TITLE
Support Embulk >0.8

### ISSUE THREAD

**Issue by yzp0n** [yuokada/embulk-output-orc#16]
Hey. Thanks for publicizing this great piece of software! We are happily using `embulk-output-orc` in our production pipeline.

We found an incompatibility issue with Embulk >0.8 which enabled "Page Scattering"[[release note](https://github.com/embulk/embulk/releases/v0.8.0)] by default.
It seems the ScatterExecutor instantiates multiple instances of the plugin and end up running `orc.Writer` in parallel, while the default `orc.MemoryManagerImpl` is *not* thread-safe [[code](https://github.com/apache/orc/blob/master/java/core/src/java/org/apache/orc/impl/MemoryManagerImpl.java#L41)].
With Embulk >0.8, we get a lot of "Wrong Owner Thread" warnings [[code](https://github.com/apache/orc/blob/master/java/core/src/java/org/apache/orc/impl/MemoryManagerImpl.java#L100)], and random crashes when finalizing the write.

If you are open to contributions, we are happy to collaborate on a fix. We have a tentative fix which seems to be working on our prod, which we'll open a PR shortly.

(突然の Issue 失礼いたします。日本語のやりとりを希望される場合は、お申し付けください。)

**Comment by yuokada** [comment]
@yzp0n Thanks you for your contribution. I merged your PR.

**Comment by yzp0n** [comment]
Thank you for the merge! Let me close this issue as resolved.
